# Verrazzano "another" site configuration (adds to or overides "_default")

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-177109661-1"

[[params.versions]]
version = "latest"
url = "https://another/"

[[params.versions]]
version = "v0.17.2"
url = "https://another/v0.17.2"

[[params.versions]]
version = "v0.17.1"
url = "https://another/v0.17.1"

[[params.versions]]
version = "v0.17.0"
url = "https://another/v0.17.0"
