# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "bbef87cd33f0884bd"

[[versions]]
version = "latest"
url = "https://guoyongzhang.github.io/github.io/latest/docs/"

[[versions]]
version = "v0.17"
url = "https://guoyongzhang.github.io/github.io/v0.17/docs/"
